#!/bin/bash

# cd in this command's directory
cd $(dirname $0)

#Getting the env. as passed by the test framework - mostly MACADDR and NODE_ISO
CONFIG=start-qemu.conf
if [ ! -e ${CONFIG} ];then
    echo "File for MAC Address not found"
    exit 1
fi
. $CONFIG

#default Value
QEMU=qemu-system-x86_64
HDA=hda_10.raw
RAM=520;

SCRIPT=./qemu-ifup
TAP="tap,script=$SCRIPT";


##check for the creation of new HDA
#if [ -e "$HDA" ]; then
#    echo "Disk already existing removing  it..."
#    rm -rf $HDA
#fi
#

#Creating new HDA if needed only
if [ -f $HDA ] ; then
    echo "Using $HDA"
else
    echo "Creating hard disk for Qemu install under $HDA"
    img=$(qemu-img create $HDA 10G)
    if [ -z "$img" ];then
	echo "Can't Create disk image..."
	exit 1
    fi
fi

echo "New $HDA is created..."

#Command for running the Qemu Emulator
ARGS="-boot d -cdrom ${NODE_ISO} -hda ${HDA} -m ${RAM}  -net nic,macaddr=${MACADDR} -net $TAP -nographic -pidfile qemu.pid"
echo $$ > shell.pid
echo "Running $QEMU $ARGS < /dev/null"
exec $QEMU $ARGS < /dev/null
