#!/bin/bash
cd $(dirname $0)
python -c "import time; print int(time.time())" > timestamp
mkdir -p logs
time=$(date +%H-%M)
runfile=run-${time}.txt
runlast=run
tracefile=trace-${time}.txt
tracelast=trace

# figure if TestMain succeeds, as the retcod gets lost in the pipe
rm -f logs/success
rm -f logs/$runlast; (cd logs; ln -s $runfile $runlast)
rm -f logs/$tracelast; (cd logs; ln -s $tracefile $tracelast)
python -u TestMain.py -t logs/$tracefile "$@" &> logs/$runfile && touch logs/success
cat logs/$runfile

if [ -f logs/success ] ; then
    exit 0
else
    exit 1
fi
